Repository sigma-webdev/netflix-clone, pull requests merged in 2023-06, with the labels that each got.

#77 handle default value for movie content and series
  backend/controller/contentController.js
  backend/model/contentSchema.js
  backend/utils/getVideoLength.js
Labels: enhancement, fix, update

#83 Feature/movie
  backend/controller/contentController.js
  backend/utils/getVideoLength.js
  backend/utils/likeDislike.js
Labels: enhancement, fix, update

#87 Fixes/shivam
  backend/controller/authController.js
Labels: fix

#84 Payment backend
  backend/app.js
  backend/controller/paymentController.js
  backend/controller/usercontroller.js
  backend/middleware/authAdmin.js
  backend/middleware/authorizeRoles.js
  backend/middleware/ckeckUserSubscribtion.js
  backend/model/subscriptionPlanSchema.js
  backend/model/userSchema.js
  backend/router/contentRouter.js
  backend/router/paymentRouter.js
  backend/router/userRouter.js
Labels: add feature

#94 updated auth and authorize route
  backend/controller/contentController.js
  backend/router/contentRouter.js
Labels: wontfix, update
